# Generated by Django 4.2.1 on 2023-07-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.CharField(default='NULL', max_length=50, verbose_name='Student Roll NO.'),
        ),
    ]
